
services:
###########################
# Setup the laravel container
###########################
    laravel:
        container_name: ${NAME_PROJECT}_laravel
        restart: always
        build: 
            context: ./.docker/images/laravel/
            args:
                - VALUE_PHP_VERSION=${VALUE_PHP_VERSION}
                - VALUE_XDEBUG_VERSION=${VALUE_XDEBUG_VERSION}
                - VALUE_COMPOSER_VERSION=${VALUE_COMPOSER_VERSION}
                - VALUE_MHSEND_VERSION=${VALUE_MHSENDMAIL_VERSION}
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./config/data:/docker-entrypoint-initdata.d:rw
            - ./config/.env.local.example:/usr/local/apache2/www/.env.local.example
            - ./config/dockercron:/var/docker/cron/dockercron:rw
            - ./.docker/containers/laravel/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
            - ./.docker/containers/laravel/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/containers/laravel/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./.docker/containers/laravel/mailhog.ini:/usr/local/etc/php/conf.d/mailhog.ini:ro
            - ./.dockertmp/log/laravel:/var/log/docker/php:rw
            - ./.dockertmp/log/xdebug:/var/log/docker/xdebug:rw
            - ./.dockertmp/tmp/laravel:/var/tmp/docker/php:rw
        ports:
            - ${VALUE_LARAVEL_PORT}:8000
        environment:
            - TZ=${VALUE_TIMEZONES}
            - PHP_FOLDER_DATA=${FOLDER_DATA}
            - PHP_SGBD_DATABASE=${SGBD_DATABASE}
            - PHP_SGBD_PASSWORD=${SGBD_PASSWORD}
            - PHP_SGBD_USER=root
            - PHP_SGBD_HOST=${NAME_PROJECT}_mariadb
            - PHP_NAME_PROJECT=${NAME_PROJECT}

            
###########################
# Setup the Database (MariaDB) container
###########################
    mariadb:
        container_name: ${NAME_PROJECT}_mariadb
        restart: always
        image: mariadb:${VALUE_MARIABD_VERSION}
        volumes:
            - ./.docker/containers/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
            - ./config/sgbd_data:/docker-entrypoint-initdb.d/:rw
            - ./.dockertmp/log/mariadb:/var/log/mariadb:rw
            - ./.dockertmp/tmp/mariadb:/var/tmp/mariadb:rw
            - ./.dockertmp/mariadb_data:/var/lib/mysql
        environment:
            - TZ=${VALUE_TIMEZONES}
            - MYSQL_DATABASE=${SGBD_DATABASE}
            - MYSQL_ROOT_PASSWORD=${SGBD_PASSWORD}
            
###########################
# Setup the PhpMyAdmin container
###########################
    myadmin:
        container_name: ${NAME_PROJECT}_phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:${VALUE_PHPMYADMIN_VERSION}
        environment:
            - PMA_PORT=3306
            - PMA_HOST=${NAME_PROJECT}_mariadb
            - PMA_USER=root
            - PMA_PASSWORD=${SGBD_PASSWORD}
        ports:
            - ${VALUE_PHPMYADMIN_PORT}:80
        depends_on: 
            - mariadb
            
###########################
# Setup the mailhog container
###########################
    mailhog:
        build:
            context: .docker/images/mailhog
            args:
                - VALUE_MHOG_VERSION=${VALUE_MAILHOG_VERSION}
                - VALUE_UBUNTU_VERSION=latest
        container_name: ${NAME_PROJECT}_mailhog
        restart: always
        volumes:
            - ./.dockertmp/mailhog:/mailhog
            - ./config/email_data:/docker-entrypoint-initdata.d:rw
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/mailhog
        ports:
            - ${VALUE_MAILHOG_PORT}:8025
            
